Created a logo and added it to the title.
vinayakgavariya/PlaylistAdda pull request #26
Opened 2022-10-03 19:50 UTC by mgilberties

**Description**

- Made a logo in Illustrator.
- Removed some invalid HTML.
- Added the logo to the title section.
- Updated the styles.

**Related issue(s)**

Resolves #21

2022-10-03 19:59 UTC, VG-1 requested changes
hey @mgilberties glad you want to contribute to it.
but I don't want to change the header of the website.
instead I want to change the logo which comes in the tab of the browser along with the website name.

2022-10-03 20:02 UTC, mgilberties commented
@VG-1  Ahhh sorry, it was the terminology that threw me off course. You are after a Favicon, not a logo. I will change my push to reflect this.

2022-10-04 05:17 UTC, VG-1 commented
hey @mgilberties my bad sorry
Can you just send a video or gif how does favicon looks like.
Also push your commit to latest changes of the repo to avoid merge conflicts.

2022-10-07 03:21 UTC, VG-1 commented
Hey @mgilberties are you working on it?

2022-10-07 08:02 UTC, mgilberties commented
@VG-1 feel free to unassign this and let someone else have a go.

2025-01-08 13:31 UTC, closed without merging